### ISSUE TITLE
Use Microsoft's new open source JDBC driver with Java 8

### ISSUE THREAD

**Issue by pleira** [ruddell/generator-jhipster-mssql#1]
Now that Microsoft has open sourced the SQLServer JDBC driver for Java 8, it would be convenient to switch to that driver. The sources are located at github's [MSSQL-JDBC project](https://github.com/Microsoft/mssql-jdbc). From there, the new maven dependencies should look like:
```xml
<dependency>
    <groupId>com.microsoft.sqlserver</groupId>
    <artifactId>mssql-jdbc</artifactId>
    <version>6.1.0.jre8</version>
</dependency>
```

**Comment by ruddell** [comment]
Thank you.  Hopefully this will be integrated into the main generator soon. 😄 

Fixed https://github.com/ruddell/generator-jhipster-mssql/commit/099330246fdbc229e2a9b13478db4904b8a8e0d3
